export { default as Hero } from "./Hero/Hero"
export { default as Features } from "./Features/Features"
export { default as Collection } from "./Collection/Collection"
export { default as YourSpace } from "./YourSpace/YourSpace"
export { default as Products } from "./Products/Products"
export { default as Services } from "./Services/Services"
export { default as Newsletter } from "./Newsletter/Newsletter"